name: Build and Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify setup.py presence
        run: |
          ls -la   # Lists all files to verify setup.py is in the root
          cat setup.py  # Output setup.py content to ensure it's found

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
